version: '2.1'
services:
  node1:
    build: node1
    container_name: quorumbasicdocker
#    volumes:
#      - ./node1:/gethdockerbasicnode1
    ports:
      - "9501:9501"
  txnode1:
    build: txnode1
    container_name: quorumtxnode
    volumes:
      - 